emit:
  - "@wictorwilen/typespec-emit-json-samples"
options:
  "@wictorwilen/typespec-emit-json-samples":
    "namespace": 
      - Samples
    "models":
      - Car
      - Person
      - Store
      - Address
    "outDir": "{cwd}/output"
    "setUndefinedToNull": true